### ISSUE TITLE
context for dotted names parsed incorrectly?

### ISSUE THREAD

**Issue by johnnychen94** [jverzani/Mustache.jl#143]
I'm not sure if Mustache is expected to support this usage:

```julia
julia> render("Hello, {{ name }}!", Dict("name"=>"world"))
┌ Info: debug
│   token = Mustache.TagToken("name", "name", "{{", "}}", "")
│   tokenValue = "name"
│   context = Mustache.Context(Dict("name" => "world"), nothing, Dict{Any, Any}("name" => "world", "." => Dict("name" => "world")))
└   value = "world"
"Hello, world!"

julia> render("Hello, {{ values.name }}!", Dict("values.name"=>"world"))
┌ Info: debug
│   token = Mustache.TagToken("name", "values.name", "{{", "}}", "")
│   tokenValue = "values.name"
│   context = Mustache.Context(Dict("values.name" => "world"), nothing, Dict{Any, Any}("values.name" => nothing, "." => Dict("values.name" => "world")))
└   value = nothing
"Hello, !"
```

The debug print is done by inserting `@info "debug" token tokenValue context value` in https://github.com/jverzani/Mustache.jl/blob/55a2aa630064eb0d76f52cff6fc0eaad14ba7908/src/tokens.jl#L664-L669

**Comment by jverzani** [comment]
In https://github.com/jverzani/Mustache.jl/blob/master/src/context.jl#L58 there is check if the key has a "." in it, and if so it splits on the "." and proceeds from there. It might make sense to first see if the key with a dot is in the view and if so, return that value and if not, proceed from there. I'll have a run at that when I get a chance and see if that breaks any of the tests. It is probably best to avoid names with "." in them, as that has special meaning in Julia, but maybe you have inherited that naming scheme from elsewhere, e.g. some R data set.

**Comment by johnnychen94** [comment]
For my very specific usage, I'm trying to build a CI configuration parser that looks similar to the Github action syntax:

```toml
[[tasks]]
    runner = "shell"
    [tasks.matrix]
        script = ["rand.jl", "sum.jl"]
        length = ["64", "128", "256", "512", "1024", "2048", "4096"]
        [[tasks.matrix.includes]]
            script = "sum.jl"
            length = "8192"
        [[tasks.matrix.excludes]]
            script = "rand.jl"
            length = "4096"
    [tasks.run]
        command = "julia --startup=no --project=. scripts/julia/${{ matrix.script }} ${{ matrix.length }}"
```

where I want to substitute all `${{ ... }}` occurrences with the corresponding values.

I currently use a simple `replace` implementation to do this.
